/**
 * This file is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This file implements the functions for encoding and decoding the
 * 'SERVER_RESPONSE_with_header' message type. See informationPacket.h for more details.
 */

#include <message.h>
#include "informationPacket.h"

uint16_t infopacket_header_dest_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 0, 16);
}

void infopacket_header_dest_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 0, 16, value);
}

uint16_t infopacket_header_src_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 16, 16);
}

void infopacket_header_src_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 16, 16, value);
}

uint8_t infopacket_header_length_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 32, 8);
}

void infopacket_header_length_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 32, 8, value);
}

uint8_t infopacket_header_group_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 40, 8);
}

void infopacket_header_group_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 40, 8, value);
}

uint8_t infopacket_header_type_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 48, 8);
}

void infopacket_header_type_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 48, 8, value);
}

uint8_t infopacket_packet_type_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 56, 8);
}

void infopacket_packet_type_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 56, 8, value);
}

uint16_t infopacket_control_nodeID_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 64, 16);
}

void infopacket_control_nodeID_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 64, 16, value);
}

uint16_t infopacket_server_nodeID_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 80, 16);
}

void infopacket_server_nodeID_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 80, 16, value);
}

uint8_t infopacket_reply_length_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 96, 8);
}

void infopacket_reply_length_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 96, 8, value);
}

size_t infopacket_reply_offset(size_t index1)
{
  return infopacket_reply_offsetbits(index1) / 8;
}

uint8_t infopacket_reply_get(tmsg_t *msg, size_t index1)
{
  return tmsg_read_ube(msg, infopacket_reply_offsetbits(index1), 8);
}

void infopacket_reply_set(tmsg_t *msg, size_t index1, uint8_t value)
{
  tmsg_write_ube(msg, infopacket_reply_offsetbits(index1), 8, value);
}

size_t infopacket_reply_offsetbits(size_t index1)
{
  size_t offset = 104;
  if (index1 >= 60) { tmsg_fail(); return (size_t)-1; }
  offset += 0 + index1 * 8;
  return offset;
}

