/**
 * This file is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This file implements the functions for encoding and decoding the
 * 'CONTROL_INSTRUCTION_with_header' message type. See instructionPacket.h for more details.
 */

#include <message.h>
#include "instructionPacket.h"

uint16_t cmdpacket_header_dest_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 0, 16);
}

void cmdpacket_header_dest_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 0, 16, value);
}

uint16_t cmdpacket_header_src_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 16, 16);
}

void cmdpacket_header_src_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 16, 16, value);
}

uint8_t cmdpacket_header_length_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 32, 8);
}

void cmdpacket_header_length_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 32, 8, value);
}

uint8_t cmdpacket_header_group_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 40, 8);
}

void cmdpacket_header_group_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 40, 8, value);
}

uint8_t cmdpacket_header_type_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 48, 8);
}

void cmdpacket_header_type_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 48, 8, value);
}

uint8_t cmdpacket_packet_type_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 56, 8);
}

void cmdpacket_packet_type_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 56, 8, value);
}

uint8_t cmdpacket_control_instruction_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 64, 8);
}

void cmdpacket_control_instruction_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 64, 8, value);
}

uint16_t cmdpacket_server_nodeID_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 72, 16);
}

void cmdpacket_server_nodeID_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 72, 16, value);
}

uint8_t cmdpacket_command_length_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 88, 8);
}

void cmdpacket_command_length_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 88, 8, value);
}

size_t cmdpacket_command_content_offset(size_t index1)
{
  return cmdpacket_command_content_offsetbits(index1) / 8;
}

uint8_t cmdpacket_command_content_get(tmsg_t *msg, size_t index1)
{
  return tmsg_read_ube(msg, cmdpacket_command_content_offsetbits(index1), 8);
}

void cmdpacket_command_content_set(tmsg_t *msg, size_t index1, uint8_t value)
{
  tmsg_write_ube(msg, cmdpacket_command_content_offsetbits(index1), 8, value);
}

size_t cmdpacket_command_content_offsetbits(size_t index1)
{
  size_t offset = 96;
  if (index1 >= 20) { tmsg_fail(); return (size_t)-1; }
  offset += 0 + index1 * 8;
  return offset;
}

