COMPONENT=anchorAppC
CFLAGS += -DTOSH_DATA_LENGTH=100\
		  -DCC2420_DEF_RFPOWER=7\
		  -I$(TOSDIR)/lib/net/le \
		  -I$(TOSDIR)/lib/net \
		  -I$(TOSDIR)/lib/net/drip \
		  -I$(TOSDIR)/lib/net/ctp \
		  -I$(CURDIR)/../ 

#BOOTLOADER=tosboot

include $(MAKERULES)
