COMPONENT=controlAppC
CFLAGS += -DTOSH_DATA_LENGTH=70\
		  -DCC2420_DEF_RFPOWER=3\
		  -I$(TOSDIR)/lib/net/le \
		  -I$(TOSDIR)/lib/net \
		  -I$(TOSDIR)/lib/net/drip \
		  -I$(TOSDIR)/lib/net/ctp \
		  -I$(CURDIR)/../ 

include $(MAKERULES)
