/**
 * This file is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This file defines the layout of the 'ANCHOR_DECISION_with_header' message type.
 */

#ifndef DCSPACKET_H
#define DCSPACKET_H
#include <message.h>

enum {
  /** The default size of this message type in bytes. */
  DCSPACKET_SIZE = 11,

  /** The Active Message type associated with this message. */
  DCSPACKET_AM_TYPE = -1,

  /* Field header.dest: type uint16_t, offset (bits) 0, size (bits) 16 */
  /** Offset (in bytes) of the field 'header.dest' */
  DCSPACKET_HEADER_DEST_OFFSET = 0,
  /** Offset (in bits) of the field 'header.dest' */
  DCSPACKET_HEADER_DEST_OFFSETBITS = 0,
  /** Size (in bytes) of the field 'header.dest' */
  DCSPACKET_HEADER_DEST_SIZE = 2,
  /** Size (in bits) of the field 'header.dest' */
  DCSPACKET_HEADER_DEST_SIZEBITS = 16,

  /* Field header.src: type uint16_t, offset (bits) 16, size (bits) 16 */
  /** Offset (in bytes) of the field 'header.src' */
  DCSPACKET_HEADER_SRC_OFFSET = 2,
  /** Offset (in bits) of the field 'header.src' */
  DCSPACKET_HEADER_SRC_OFFSETBITS = 16,
  /** Size (in bytes) of the field 'header.src' */
  DCSPACKET_HEADER_SRC_SIZE = 2,
  /** Size (in bits) of the field 'header.src' */
  DCSPACKET_HEADER_SRC_SIZEBITS = 16,

  /* Field header.length: type uint8_t, offset (bits) 32, size (bits) 8 */
  /** Offset (in bytes) of the field 'header.length' */
  DCSPACKET_HEADER_LENGTH_OFFSET = 4,
  /** Offset (in bits) of the field 'header.length' */
  DCSPACKET_HEADER_LENGTH_OFFSETBITS = 32,
  /** Size (in bytes) of the field 'header.length' */
  DCSPACKET_HEADER_LENGTH_SIZE = 1,
  /** Size (in bits) of the field 'header.length' */
  DCSPACKET_HEADER_LENGTH_SIZEBITS = 8,

  /* Field header.group: type uint8_t, offset (bits) 40, size (bits) 8 */
  /** Offset (in bytes) of the field 'header.group' */
  DCSPACKET_HEADER_GROUP_OFFSET = 5,
  /** Offset (in bits) of the field 'header.group' */
  DCSPACKET_HEADER_GROUP_OFFSETBITS = 40,
  /** Size (in bytes) of the field 'header.group' */
  DCSPACKET_HEADER_GROUP_SIZE = 1,
  /** Size (in bits) of the field 'header.group' */
  DCSPACKET_HEADER_GROUP_SIZEBITS = 8,

  /* Field header.type: type uint8_t, offset (bits) 48, size (bits) 8 */
  /** Offset (in bytes) of the field 'header.type' */
  DCSPACKET_HEADER_TYPE_OFFSET = 6,
  /** Offset (in bits) of the field 'header.type' */
  DCSPACKET_HEADER_TYPE_OFFSETBITS = 48,
  /** Size (in bytes) of the field 'header.type' */
  DCSPACKET_HEADER_TYPE_SIZE = 1,
  /** Size (in bits) of the field 'header.type' */
  DCSPACKET_HEADER_TYPE_SIZEBITS = 8,

  /* Field packet_type: type uint8_t, offset (bits) 56, size (bits) 8 */
  /** Offset (in bytes) of the field 'packet_type' */
  DCSPACKET_PACKET_TYPE_OFFSET = 7,
  /** Offset (in bits) of the field 'packet_type' */
  DCSPACKET_PACKET_TYPE_OFFSETBITS = 56,
  /** Size (in bytes) of the field 'packet_type' */
  DCSPACKET_PACKET_TYPE_SIZE = 1,
  /** Size (in bits) of the field 'packet_type' */
  DCSPACKET_PACKET_TYPE_SIZEBITS = 8,

  /* Field control_nodeID: type uint16_t[], element size (bits) 16 */
  /** Elementsize (in bytes) of the field 'control_nodeID' */
  DCSPACKET_CONTROL_NODEID_ELEMENTSIZE = 2,
  /** Elementsize (in bits) of the field 'control_nodeID' */
  DCSPACKET_CONTROL_NODEID_ELEMENTSIZEBITS = 16,
  /** The number of dimensions in the array 'control_nodeID'. */
  DCSPACKET_CONTROL_NODEID_NUMDIMENSIONS = 1,
  /** Number of elements in dimension 1 of array 'control_nodeID'. */
  DCSPACKET_CONTROL_NODEID_NUMELEMENTS_1 = 1,
  /** Total number of elements in the array 'control_nodeID'. */
  DCSPACKET_CONTROL_NODEID_NUMELEMENTS = 1,

  /* Field decision: type uint8_t[], element size (bits) 8 */
  /** Elementsize (in bytes) of the field 'decision' */
  DCSPACKET_DECISION_ELEMENTSIZE = 1,
  /** Elementsize (in bits) of the field 'decision' */
  DCSPACKET_DECISION_ELEMENTSIZEBITS = 8,
  /** The number of dimensions in the array 'decision'. */
  DCSPACKET_DECISION_NUMDIMENSIONS = 1,
  /** Number of elements in dimension 1 of array 'decision'. */
  DCSPACKET_DECISION_NUMELEMENTS_1 = 1,
  /** Total number of elements in the array 'decision'. */
  DCSPACKET_DECISION_NUMELEMENTS = 1,
};

/**
 * Return the value of the field 'header.dest'
 */
uint16_t dcspacket_header_dest_get(tmsg_t *msg);

/**
 * Set the value of the field 'header.dest'
 */
void dcspacket_header_dest_set(tmsg_t *msg, uint16_t value);

/**
 * Return the value of the field 'header.src'
 */
uint16_t dcspacket_header_src_get(tmsg_t *msg);

/**
 * Set the value of the field 'header.src'
 */
void dcspacket_header_src_set(tmsg_t *msg, uint16_t value);

/**
 * Return the value of the field 'header.length'
 */
uint8_t dcspacket_header_length_get(tmsg_t *msg);

/**
 * Set the value of the field 'header.length'
 */
void dcspacket_header_length_set(tmsg_t *msg, uint8_t value);

/**
 * Return the value of the field 'header.group'
 */
uint8_t dcspacket_header_group_get(tmsg_t *msg);

/**
 * Set the value of the field 'header.group'
 */
void dcspacket_header_group_set(tmsg_t *msg, uint8_t value);

/**
 * Return the value of the field 'header.type'
 */
uint8_t dcspacket_header_type_get(tmsg_t *msg);

/**
 * Set the value of the field 'header.type'
 */
void dcspacket_header_type_set(tmsg_t *msg, uint8_t value);

/**
 * Return the value of the field 'packet_type'
 */
uint8_t dcspacket_packet_type_get(tmsg_t *msg);

/**
 * Set the value of the field 'packet_type'
 */
void dcspacket_packet_type_set(tmsg_t *msg, uint8_t value);

/**
 * Return the byte offset of an element of array 'control_nodeID'
 */
size_t dcspacket_control_nodeID_offset(size_t index1);

/**
 * Return an element of the array 'control_nodeID'
 */
uint16_t dcspacket_control_nodeID_get(tmsg_t *msg, size_t index1);

/**
 * Set an element of the array 'control_nodeID'
 */
void dcspacket_control_nodeID_set(tmsg_t *msg, size_t index1, uint16_t value);

/**
 * Return the bit offset of an element of array 'control_nodeID'
 */
size_t dcspacket_control_nodeID_offsetbits(size_t index1);

/**
 * Return the byte offset of an element of array 'decision'
 */
size_t dcspacket_decision_offset(size_t index1);

/**
 * Return an element of the array 'decision'
 */
uint8_t dcspacket_decision_get(tmsg_t *msg, size_t index1);

/**
 * Set an element of the array 'decision'
 */
void dcspacket_decision_set(tmsg_t *msg, size_t index1, uint8_t value);

/**
 * Return the bit offset of an element of array 'decision'
 */
size_t dcspacket_decision_offsetbits(size_t index1);

#endif
