/**
 * This file is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This file implements the functions for encoding and decoding the
 * 'ANCHOR_DECISION_with_header' message type. See decisionPacket.h for more details.
 */

#include <message.h>
#include "decisionPacket.h"

uint16_t dcspacket_header_dest_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 0, 16);
}

void dcspacket_header_dest_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 0, 16, value);
}

uint16_t dcspacket_header_src_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 16, 16);
}

void dcspacket_header_src_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 16, 16, value);
}

uint8_t dcspacket_header_length_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 32, 8);
}

void dcspacket_header_length_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 32, 8, value);
}

uint8_t dcspacket_header_group_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 40, 8);
}

void dcspacket_header_group_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 40, 8, value);
}

uint8_t dcspacket_header_type_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 48, 8);
}

void dcspacket_header_type_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 48, 8, value);
}

uint8_t dcspacket_packet_type_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 56, 8);
}

void dcspacket_packet_type_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 56, 8, value);
}

size_t dcspacket_control_nodeID_offset(size_t index1)
{
  return dcspacket_control_nodeID_offsetbits(index1) / 8;
}

uint16_t dcspacket_control_nodeID_get(tmsg_t *msg, size_t index1)
{
  return tmsg_read_ube(msg, dcspacket_control_nodeID_offsetbits(index1), 16);
}

void dcspacket_control_nodeID_set(tmsg_t *msg, size_t index1, uint16_t value)
{
  tmsg_write_ube(msg, dcspacket_control_nodeID_offsetbits(index1), 16, value);
}

size_t dcspacket_control_nodeID_offsetbits(size_t index1)
{
  size_t offset = 64;
  if (index1 >= 1) { tmsg_fail(); return (size_t)-1; }
  offset += 0 + index1 * 16;
  return offset;
}

size_t dcspacket_decision_offset(size_t index1)
{
  return dcspacket_decision_offsetbits(index1) / 8;
}

uint8_t dcspacket_decision_get(tmsg_t *msg, size_t index1)
{
  return tmsg_read_ube(msg, dcspacket_decision_offsetbits(index1), 8);
}

void dcspacket_decision_set(tmsg_t *msg, size_t index1, uint8_t value)
{
  tmsg_write_ube(msg, dcspacket_decision_offsetbits(index1), 8, value);
}

size_t dcspacket_decision_offsetbits(size_t index1)
{
  size_t offset = 80;
  if (index1 >= 1) { tmsg_fail(); return (size_t)-1; }
  offset += 0 + index1 * 8;
  return offset;
}

