/**
 * This file is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This file implements the functions for encoding and decoding the
 * 'ANCHOR_POSINFO_with_header' message type. See infoPacket.h for more details.
 */

#include <message.h>
#include "infoPacket.h"

uint16_t infopacket_header_dest_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 0, 16);
}

void infopacket_header_dest_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 0, 16, value);
}

uint16_t infopacket_header_src_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 16, 16);
}

void infopacket_header_src_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 16, 16, value);
}

uint8_t infopacket_header_length_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 32, 8);
}

void infopacket_header_length_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 32, 8, value);
}

uint8_t infopacket_header_group_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 40, 8);
}

void infopacket_header_group_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 40, 8, value);
}

uint8_t infopacket_header_type_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 48, 8);
}

void infopacket_header_type_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 48, 8, value);
}

uint8_t infopacket_packet_type_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 56, 8);
}

void infopacket_packet_type_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 56, 8, value);
}

size_t infopacket_rssiList_offset(size_t index1, size_t index2)
{
  return infopacket_rssiList_offsetbits(index1, index2) / 8;
}

uint16_t infopacket_rssiList_get(tmsg_t *msg, size_t index1, size_t index2)
{
  return tmsg_read_ube(msg, infopacket_rssiList_offsetbits(index1, index2), 16);
}

void infopacket_rssiList_set(tmsg_t *msg, size_t index1, size_t index2, uint16_t value)
{
  tmsg_write_ube(msg, infopacket_rssiList_offsetbits(index1, index2), 16, value);
}

size_t infopacket_rssiList_offsetbits(size_t index1, size_t index2)
{
  size_t offset = 64;
  if (index1 >= 5) { tmsg_fail(); return (size_t)-1; }
  offset += 0 + index1 * 80;
  if (index2 >= 5) { tmsg_fail(); return (size_t)-1; }
  offset += 0 + index2 * 16;
  return offset;
}

