/**
 * This file is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This file defines the layout of the 'test_serial_msg_with_header' message type.
 */

#ifndef SPACKET_H
#define SPACKET_H
#include <message.h>

enum {
  /** The default size of this message type in bytes. */
  SPACKET_SIZE = 20,

  /** The Active Message type associated with this message. */
  SPACKET_AM_TYPE = -1,

  /* Field header.dest: type uint16_t, offset (bits) 0, size (bits) 16 */
  /** Offset (in bytes) of the field 'header.dest' */
  SPACKET_HEADER_DEST_OFFSET = 0,
  /** Offset (in bits) of the field 'header.dest' */
  SPACKET_HEADER_DEST_OFFSETBITS = 0,
  /** Size (in bytes) of the field 'header.dest' */
  SPACKET_HEADER_DEST_SIZE = 2,
  /** Size (in bits) of the field 'header.dest' */
  SPACKET_HEADER_DEST_SIZEBITS = 16,

  /* Field header.src: type uint16_t, offset (bits) 16, size (bits) 16 */
  /** Offset (in bytes) of the field 'header.src' */
  SPACKET_HEADER_SRC_OFFSET = 2,
  /** Offset (in bits) of the field 'header.src' */
  SPACKET_HEADER_SRC_OFFSETBITS = 16,
  /** Size (in bytes) of the field 'header.src' */
  SPACKET_HEADER_SRC_SIZE = 2,
  /** Size (in bits) of the field 'header.src' */
  SPACKET_HEADER_SRC_SIZEBITS = 16,

  /* Field header.length: type uint8_t, offset (bits) 32, size (bits) 8 */
  /** Offset (in bytes) of the field 'header.length' */
  SPACKET_HEADER_LENGTH_OFFSET = 4,
  /** Offset (in bits) of the field 'header.length' */
  SPACKET_HEADER_LENGTH_OFFSETBITS = 32,
  /** Size (in bytes) of the field 'header.length' */
  SPACKET_HEADER_LENGTH_SIZE = 1,
  /** Size (in bits) of the field 'header.length' */
  SPACKET_HEADER_LENGTH_SIZEBITS = 8,

  /* Field header.group: type uint8_t, offset (bits) 40, size (bits) 8 */
  /** Offset (in bytes) of the field 'header.group' */
  SPACKET_HEADER_GROUP_OFFSET = 5,
  /** Offset (in bits) of the field 'header.group' */
  SPACKET_HEADER_GROUP_OFFSETBITS = 40,
  /** Size (in bytes) of the field 'header.group' */
  SPACKET_HEADER_GROUP_SIZE = 1,
  /** Size (in bits) of the field 'header.group' */
  SPACKET_HEADER_GROUP_SIZEBITS = 8,

  /* Field header.type: type uint8_t, offset (bits) 48, size (bits) 8 */
  /** Offset (in bytes) of the field 'header.type' */
  SPACKET_HEADER_TYPE_OFFSET = 6,
  /** Offset (in bits) of the field 'header.type' */
  SPACKET_HEADER_TYPE_OFFSETBITS = 48,
  /** Size (in bytes) of the field 'header.type' */
  SPACKET_HEADER_TYPE_SIZE = 1,
  /** Size (in bits) of the field 'header.type' */
  SPACKET_HEADER_TYPE_SIZEBITS = 8,

  /* Field counter: type uint16_t, offset (bits) 56, size (bits) 16 */
  /** Offset (in bytes) of the field 'counter' */
  SPACKET_COUNTER_OFFSET = 7,
  /** Offset (in bits) of the field 'counter' */
  SPACKET_COUNTER_OFFSETBITS = 56,
  /** Size (in bytes) of the field 'counter' */
  SPACKET_COUNTER_SIZE = 2,
  /** Size (in bits) of the field 'counter' */
  SPACKET_COUNTER_SIZEBITS = 16,

  /* Field message: type uint8_t[], element size (bits) 8 */
  /** Elementsize (in bytes) of the field 'message' */
  SPACKET_MESSAGE_ELEMENTSIZE = 1,
  /** Elementsize (in bits) of the field 'message' */
  SPACKET_MESSAGE_ELEMENTSIZEBITS = 8,
  /** The number of dimensions in the array 'message'. */
  SPACKET_MESSAGE_NUMDIMENSIONS = 1,
  /** Number of elements in dimension 1 of array 'message'. */
  SPACKET_MESSAGE_NUMELEMENTS_1 = 10,
  /** Total number of elements in the array 'message'. */
  SPACKET_MESSAGE_NUMELEMENTS = 10,

  /* Field messageLength: type uint8_t, offset (bits) 152, size (bits) 8 */
  /** Offset (in bytes) of the field 'messageLength' */
  SPACKET_MESSAGELENGTH_OFFSET = 19,
  /** Offset (in bits) of the field 'messageLength' */
  SPACKET_MESSAGELENGTH_OFFSETBITS = 152,
  /** Size (in bytes) of the field 'messageLength' */
  SPACKET_MESSAGELENGTH_SIZE = 1,
  /** Size (in bits) of the field 'messageLength' */
  SPACKET_MESSAGELENGTH_SIZEBITS = 8,
};

/**
 * Return the value of the field 'header.dest'
 */
uint16_t spacket_header_dest_get(tmsg_t *msg);

/**
 * Set the value of the field 'header.dest'
 */
void spacket_header_dest_set(tmsg_t *msg, uint16_t value);

/**
 * Return the value of the field 'header.src'
 */
uint16_t spacket_header_src_get(tmsg_t *msg);

/**
 * Set the value of the field 'header.src'
 */
void spacket_header_src_set(tmsg_t *msg, uint16_t value);

/**
 * Return the value of the field 'header.length'
 */
uint8_t spacket_header_length_get(tmsg_t *msg);

/**
 * Set the value of the field 'header.length'
 */
void spacket_header_length_set(tmsg_t *msg, uint8_t value);

/**
 * Return the value of the field 'header.group'
 */
uint8_t spacket_header_group_get(tmsg_t *msg);

/**
 * Set the value of the field 'header.group'
 */
void spacket_header_group_set(tmsg_t *msg, uint8_t value);

/**
 * Return the value of the field 'header.type'
 */
uint8_t spacket_header_type_get(tmsg_t *msg);

/**
 * Set the value of the field 'header.type'
 */
void spacket_header_type_set(tmsg_t *msg, uint8_t value);

/**
 * Return the value of the field 'counter'
 */
uint16_t spacket_counter_get(tmsg_t *msg);

/**
 * Set the value of the field 'counter'
 */
void spacket_counter_set(tmsg_t *msg, uint16_t value);

/**
 * Return the byte offset of an element of array 'message'
 */
size_t spacket_message_offset(size_t index1);

/**
 * Return an element of the array 'message'
 */
uint8_t spacket_message_get(tmsg_t *msg, size_t index1);

/**
 * Set an element of the array 'message'
 */
void spacket_message_set(tmsg_t *msg, size_t index1, uint8_t value);

/**
 * Return the bit offset of an element of array 'message'
 */
size_t spacket_message_offsetbits(size_t index1);

/**
 * Return the value of the field 'messageLength'
 */
uint8_t spacket_messageLength_get(tmsg_t *msg);

/**
 * Set the value of the field 'messageLength'
 */
void spacket_messageLength_set(tmsg_t *msg, uint8_t value);

#endif
